name: Generate Profile Card Screenshot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Clean Puppeteer cache
        run: rm -rf node_modules/puppeteer/.local-chromium || true

      - name: Generate screenshot
        run: node screenshot.js profile-card.html

      - name: Commit and push screenshot
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update latest profile card screenshot"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          branch: main
          file_pattern: latest.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
